# Generated by Django 3.1.6 on 2021-02-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityperiod',
            table='ActivityPeriod',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
